# Generated by Django 4.1.5 on 2024-03-18 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HospitalBookings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=250, null=True)),
                ('last_name', models.CharField(max_length=250, null=True)),
                ('email', models.CharField(max_length=250, null=True, unique=True)),
                ('mobile_number', models.CharField(max_length=250, null=True, unique=True)),
                ('doctor_booked', models.CharField(max_length=250, null=True)),
                ('appointment_type', models.CharField(max_length=250, null=True)),
                ('appointment_time', models.DateTimeField(null=True)),
                ('preferred_contact_method', models.CharField(max_length=250, null=True)),
                ('other_appointment_detail', models.CharField(max_length=250, null=True)),
                ('emergency_contact_method', models.CharField(max_length=250, null=True)),
                ('emergency_contact', models.CharField(max_length=250, null=True)),
            ],
        ),
    ]
